[package]
name = "bioauth-flow"
version = "0.1.0"
edition = "2018"
authors = ["Humanode Team <core@humanode.io>"]
publish = false

[dependencies]
robonode-client = { version = "0.1", path = "../robonode-client" }

anyhow = "1"
async-trait = "0.1"
jsonrpc-core = "15" # TODO: update when `sc-service` bumps it's version
jsonrpc-core-client = "15" # TODO: update when `sc-service` bumps it's version
jsonrpc-derive = "15" # TODO: update when `sc-service` bumps it's version
