[package]
name = "facetec-api-client"
version = "0.1.0"
edition = "2018"
authors = ["Humanode Team <core@humanode.io>"]
publish = false

[dependencies]
bytes = "1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
assert_matches = "1.5"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
wiremock = "0.5"
