[default]
extend-ignore-identifiers-re = [".+HDNode.*"]
extend-ignore-re = ["dyn-clonable"]

[default.extend-identifiers]
# DEFLATE
"flate2" = "flate2"

[default.extend-words]
"inherents" = "inherents"

"dyn-clonable" = "dyn-clonable"

# Substrate choices we can't / won't change.
"Applyable" = "Applyable"
