[package]
name = "primitives-currency-swap"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
frame-support = { workspace = true, default-features = false }

[features]
default = ["std"]
std = ["frame-support/std"]
try-runtime = ["frame-support/try-runtime"]
