[package]
name = "frontier-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false }
pallet-ethereum = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "substrate-1a30fa2" }
sp-api = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-std = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }

[features]
default = ["std"]
std = ["codec/std", "sp-api/std", "sp-std/std", "pallet-ethereum/std"]
