[package]
name = "pallet-ethereum-chain-id"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }
frame-system = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
mockall = "0.10"
sp-core = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-io = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-runtime = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }

[features]
default = ["std"]
std = [
  "serde",
  "codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
]
try-runtime = [ "frame-support/try-runtime" ]
