[package]
name = "robonode-keygen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
robonode-crypto = { path = "../robonode-crypto" }

hex = { workspace = true, features = ["alloc"] }
rand = { workspace = true, features = ["std", "getrandom"] }
