[package]
name = "humanode-rpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
author-ext-api = { version = "0.1", path = "../author-ext-api" }
author-ext-rpc = { version = "0.1", path = "../author-ext-rpc" }
bioauth-flow-api = { version = "0.1", path = "../bioauth-flow-api" }
bioauth-flow-rpc = { version = "0.1", path = "../bioauth-flow-rpc" }
bioauth-keys = { version = "0.1", path = "../bioauth-keys" }
humanode-runtime = { version = "0.1", path = "../humanode-runtime" }
robonode-client = { version = "0.1", path = "../robonode-client" }

fc-db = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "polkadot-v0.9.36" }
fc-rpc = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "polkadot-v0.9.36" }
fc-rpc-core = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "polkadot-v0.9.36" }
fp-rpc = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "polkadot-v0.9.36" }
fp-storage = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "polkadot-v0.9.36" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
pallet-transaction-payment-rpc = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-chain-spec = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-client-api = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-consensus-babe = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-consensus-babe-rpc = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-consensus-epochs = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-finality-grandpa = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-finality-grandpa-rpc = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-network = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-rpc = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-rpc-api = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-rpc-spec-v2 = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-transaction-pool = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sc-transaction-pool-api = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-api = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-block-builder = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-blockchain = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-consensus = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-consensus-babe = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-keystore = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
substrate-frame-rpc-system = { git = "https://github.com/humanode-network/substrate", branch = "polkadot-v0.9.36" }
