[package]
name = "humanode-rpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bioauth-flow = { version = "0.1", path = "../bioauth-flow" }
humanode-runtime = { version = "0.1", path = "../humanode-runtime" }
robonode-client = { version = "0.1", path = "../robonode-client" }

jsonrpc-core = "18"
pallet-transaction-payment-rpc = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-rpc-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sc-transaction-pool-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-block-builder = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/humanode-network/substrate", branch = "master" }
substrate-frame-rpc-system = { git = "https://github.com/humanode-network/substrate", branch = "master" }
