[package]
name = "humanode-rpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
author-ext-api = { path = "../author-ext-api" }
author-ext-rpc = { path = "../author-ext-rpc" }
bioauth-flow-api = { path = "../bioauth-flow-api" }
bioauth-flow-rpc = { path = "../bioauth-flow-rpc" }
bioauth-keys = { path = "../bioauth-keys" }
evm-tracing-rpc = { path = "../evm-tracing-rpc" }
humanode-runtime = { path = "../humanode-runtime" }
robonode-client = { path = "../robonode-client" }

fc-db = { workspace = true }
fc-mapping-sync = { workspace = true }
fc-rpc = { workspace = true, features = ["rpc-binary-search-estimate"] }
fc-rpc-core = { workspace = true }
fc-storage = { workspace = true }
fp-rpc = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
pallet-transaction-payment-rpc = { workspace = true }
sc-chain-spec = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus-babe = { workspace = true }
sc-consensus-babe-rpc = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-consensus-grandpa-rpc = { workspace = true }
sc-network = { workspace = true }
sc-network-sync = { workspace = true }
sc-rpc = { workspace = true }
sc-rpc-api = { workspace = true }
sc-rpc-spec-v2 = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-core = { workspace = true }
sp-keystore = { workspace = true }
sp-runtime = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
