[package]
name = "humanode-rpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bioauth-flow = { version = "0.1", path = "../bioauth-flow" }
bioauth-flow-api = { version = "0.1", path = "../bioauth-flow-api" }
frontier-api = { version = "0.1", path = "../frontier-api" }
humanode-runtime = { version = "0.1", path = "../humanode-runtime" }
primitives-frontier = { version = "0.1", path = "../primitives-frontier" }
robonode-client = { version = "0.1", path = "../robonode-client" }

fc-db = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "substrate-1a30fa2" }
fc-rpc = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "substrate-1a30fa2" }
fc-rpc-core = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "substrate-1a30fa2" }
fp-rpc = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "substrate-1a30fa2" }
jsonrpc-core = "18"
jsonrpc-pubsub = "18.0.0"
pallet-ethereum = { default-features = false, git = "https://github.com/humanode-network/frontier", branch = "substrate-1a30fa2" }
pallet-transaction-payment-rpc = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-client-api = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-consensus-babe = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-consensus-babe-rpc = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-consensus-epochs = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-finality-grandpa = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-finality-grandpa-rpc = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-network = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-rpc = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-rpc-api = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-transaction-pool = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sc-transaction-pool-api = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-api = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-block-builder = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-blockchain = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-consensus = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-consensus-babe = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-keystore = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-runtime = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
sp-session = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
substrate-frame-rpc-system = { git = "https://github.com/humanode-network/substrate", branch = "pub-set-keys" }
