[package]
name = "eip712-common-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
eip712-common = { default-features = false, version = "0.1", path = "../eip712-common" }
primitives-ethereum = { default-features = false, version = "0.1", path = "../primitives-ethereum" }

eth-eip-712 = { package = "eip-712", version = "=0.1.0", optional = true }
hex-literal = "0.3"
secp256k1 = { version = "0.24", optional = true }
serde_json = { version = "1", optional = true }
sp-core = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }

[features]
default = ["std"]
std = ["eth-eip-712", "secp256k1", "serde_json", "eip712-common/std", "primitives-ethereum/std", "sp-core/std"]
