[package]
name = "rpc-error-response"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true }
